# Generated by Django 4.2.6 on 2023-10-13 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("turmas", "0002_turma_turma"),
    ]

    operations = [
        migrations.CreateModel(
            name="Espaco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_sala", models.CharField(max_length=50)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("A", "AUDITÓRIO"),
                            ("S", "SALA DE AULA"),
                            ("L", "LABORATÓRIO"),
                            ("G", "GINÁSIO"),
                            ("B", "BIBLIOTECA"),
                            ("V", "SALA DE VÍDEO"),
                            ("Q", "QUADRA"),
                        ],
                        default="S",
                        max_length=1,
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
                ("max_ocupacao", models.IntegerField()),
                ("disponibildiade", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.IntegerField()),
                ("descricao", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_agendamento", models.DateField()),
                ("ocupacao", models.BooleanField(default=True)),
                (
                    "espaco",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="agendamentos.espaco",
                    ),
                ),
                (
                    "horario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="agendamentos.horario",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="turmas.turma",
                    ),
                ),
            ],
        ),
    ]
