# Generated by Django 4.2.6 on 2023-10-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agendamentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="horario",
            name="ordem",
            field=models.IntegerField(unique=True),
        ),
    ]
