# Generated by Django 4.2.6 on 2023-10-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="matricula",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="tipos",
            field=models.ManyToManyField(to="usuarios.tipo"),
        ),
    ]
