# Generated by Django 4.2.6 on 2023-10-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serie",
                    models.CharField(
                        choices=[
                            ("1", "PRIMEIRO ANO"),
                            ("2", "SEGUNDO ANO"),
                            ("3", "TERCEIRO ANO"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "modalidade",
                    models.CharField(
                        choices=[("I", "INTEGRAL"), ("I.T", "INTEGRAL | TÉCNICO")],
                        max_length=3,
                    ),
                ),
                ("ano_inicio", models.IntegerField()),
                ("numero_alunos", models.IntegerField()),
            ],
        ),
    ]
