# Generated by Django 4.2.6 on 2023-10-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("turmas", "0002_turma_turma"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="turno",
            field=models.CharField(
                choices=[("M", "MATUTINO"), ("V", "VESPERTINO"), ("N", "NOTURNO")],
                default="M",
                max_length=1,
            ),
        ),
    ]
